exclude_paths:
  - tmp
  - vendor

detectors:
  FeatureEnvy:
    exclude:
      - Terminus::Actions::API::Screens::Create#handle
      - Terminus::Actions::API::Screens::Create#save
      - Terminus::Actions::Devices::Create#render_new
      - Terminus::Actions::Devices::Update#edit
      - Terminus::Actions::Firmware::Delete#render
      - Terminus::Aspects::Screens::Converter#convert
      - Terminus::Aspects::Screens::Shoter#save
      - Terminus::IPFinder#all
  LongParameterList:
    enabled: false
  TooManyStatements:
    exclude:
      - Terminus::Aspects::Firmware::Downloader#get
      - Terminus::Aspects::Screens::Converter#convert
      - Terminus::Aspects::Screens::Shoter#save
      - Terminus::Views::Parts::Device#battery_percentage
      - Terminus::Views::Parts::Device#wifi_percentage
