[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/up"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "web"

[services.variables]
HANAMI_ENV = "production"
RACK_ENV = "production"
HANAMI_SERVE_ASSETS = "true"
BUNDLE_WITHOUT = "development:quality:test:tools"