[build]
builder = "nixpacks"

[deploy]
startCommand = "bundle exec hanami server --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
