[build]
builder = "nixpacks"

[deploy]
startCommand = "run bundle exec hanami db migrate && bundle exec hanami server --host 0.0.0.0 --port $PORT"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
