--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5
-- Dumped by pg_dump version 17.5

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: firmware_kind_enum; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.firmware_kind_enum AS ENUM (
    'beta',
    'stable'
);


--
-- Name: special_function_enum; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.special_function_enum AS ENUM (
    'identify',
    'sleep',
    'add_wifi',
    'restart_playlist',
    'rewind',
    'send_to_me',
    'none'
);


--
-- Name: wake_reason_enum; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.wake_reason_enum AS ENUM (
    'powercycle',
    'all',
    'EXT0',
    'EXT1',
    'timer',
    'touchpad',
    'ulp',
    'button',
    'uart',
    'wifi',
    'cocpu',
    'cocpu_trap_trig',
    'bt'
);


--
-- Name: wifi_status_enum; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.wifi_status_enum AS ENUM (
    'no_shield',
    'idle_status',
    'no_ssid_avail',
    'scan_completed',
    'connected',
    'connect_failed',
    'connection_lost',
    'disconnected'
);


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: device_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.device_logs (
    id integer NOT NULL,
    device_id integer NOT NULL,
    external_id integer NOT NULL,
    message text NOT NULL,
    source_path text NOT NULL,
    source_line integer NOT NULL,
    retry integer DEFAULT 0 NOT NULL,
    wifi_signal integer DEFAULT 0 NOT NULL,
    wifi_status public.wifi_status_enum DEFAULT 'disconnected'::public.wifi_status_enum NOT NULL,
    refresh_rate integer DEFAULT 0 NOT NULL,
    sleep_duration integer DEFAULT 0 NOT NULL,
    firmware_version text NOT NULL,
    special_function public.special_function_enum DEFAULT 'none'::public.special_function_enum NOT NULL,
    wake_reason public.wake_reason_enum DEFAULT 'timer'::public.wake_reason_enum NOT NULL,
    battery_voltage double precision DEFAULT 0 NOT NULL,
    free_heap_size integer DEFAULT 0 NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    max_alloc_size integer DEFAULT 0 NOT NULL
);


--
-- Name: device_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.device_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.device_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: devices; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.devices (
    id integer NOT NULL,
    friendly_id text,
    label text,
    mac_address text,
    api_key text,
    firmware_version text,
    firmware_beta boolean DEFAULT false NOT NULL,
    wifi integer DEFAULT 0 NOT NULL,
    battery double precision DEFAULT 0 NOT NULL,
    refresh_rate integer DEFAULT 900 NOT NULL,
    image_timeout integer DEFAULT 0 NOT NULL,
    width integer DEFAULT 0 NOT NULL,
    height integer DEFAULT 0 NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    proxy boolean DEFAULT false NOT NULL,
    firmware_update boolean DEFAULT false NOT NULL,
    sleep_start_at time without time zone,
    sleep_end_at time without time zone
);


--
-- Name: devices_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.devices ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.devices_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: firmwares; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.firmwares (
    id integer NOT NULL,
    version text NOT NULL,
    kind public.firmware_kind_enum DEFAULT 'stable'::public.firmware_kind_enum NOT NULL,
    attachment_data jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: firmwares_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.firmwares ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.firmwares_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: model; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.model (
    id integer NOT NULL,
    name text NOT NULL,
    label text NOT NULL,
    description text,
    width integer NOT NULL,
    height integer NOT NULL,
    published_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: model_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.model ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.model_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schema_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schema_migrations (
    filename text NOT NULL
);


--
-- Name: device_logs device_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.device_logs
    ADD CONSTRAINT device_logs_pkey PRIMARY KEY (id);


--
-- Name: devices devices_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.devices
    ADD CONSTRAINT devices_pkey PRIMARY KEY (id);


--
-- Name: firmwares firmwares_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.firmwares
    ADD CONSTRAINT firmwares_pkey PRIMARY KEY (id);


--
-- Name: firmwares firmwares_version_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.firmwares
    ADD CONSTRAINT firmwares_version_key UNIQUE (version);


--
-- Name: model model_label_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model
    ADD CONSTRAINT model_label_key UNIQUE (label);


--
-- Name: model model_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model
    ADD CONSTRAINT model_name_key UNIQUE (name);


--
-- Name: model model_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model
    ADD CONSTRAINT model_pkey PRIMARY KEY (id);


--
-- Name: schema_migrations schema_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schema_migrations
    ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (filename);


--
-- Name: device_logs_device_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX device_logs_device_id_index ON public.device_logs USING btree (device_id);


--
-- Name: device_logs_special_function_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX device_logs_special_function_index ON public.device_logs USING btree (special_function);


--
-- Name: device_logs_wake_reason_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX device_logs_wake_reason_index ON public.device_logs USING btree (wake_reason);


--
-- Name: device_logs_wifi_status_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX device_logs_wifi_status_index ON public.device_logs USING btree (wifi_status);


--
-- Name: firmwares_attachment_data_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX firmwares_attachment_data_index ON public.firmwares USING gin (attachment_data);


--
-- Name: model_label_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX model_label_index ON public.model USING btree (label);


--
-- Name: model_name_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX model_name_index ON public.model USING btree (name);


--
-- Name: device_logs device_logs_device_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.device_logs
    ADD CONSTRAINT device_logs_device_id_fkey FOREIGN KEY (device_id) REFERENCES public.devices(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

SET search_path TO "$user", public;

INSERT INTO schema_migrations (filename) VALUES
('20250305150912_create_devices.rb'),
('20250324153748_create_device_logs.rb'),
('20250401150503_add_device_proxy_column.rb'),
('20250408143435_add_device_firmware_update_column.rb'),
('20250423143027_add_device_log_max_alloc_size.rb'),
('20250429114320_remove_device_setup_at_column.rb'),
('20250429115049_change_device_column_text_types.rb'),
('20250602132300_add_device_sleep_period.rb'),
('20250609143532_add_firmwares.rb'),
('20250624130848_add_model.rb');
